# Generated by Django 2.0 on 2018-12-11 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Myuser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('firstname', models.CharField(max_length=255)),
                ('lastname', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=250, unique=True)),
                ('date_of_birth', models.DateField(null=True)),
                ('date_joined', models.DateField(null=True)),
                ('last_login', models.DateField(null=True)),
                ('gender', models.CharField(max_length=10)),
                ('nationality', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=50)),
                ('is_watcher', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
