# Generated by Django 2.0 on 2019-02-19 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prod_cat_app', '0002_auto_20190219_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.ImageField(blank=True, upload_to='products/%Y/%m/%d'),
        ),
    ]
