# Generated by Django 2.2 on 2019-04-01 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_shippingaddresses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingaddresses',
            name='id',
        ),
        migrations.AlterField(
            model_name='shippingaddresses',
            name='cart',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='cart.Cart'),
        ),
    ]
