# Generated by Django 2.2 on 2019-04-08 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_my_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='my_order',
            name='order_id',
            field=models.BigIntegerField(default=(240,), verbose_name='Order Number'),
        ),
        migrations.AlterField(
            model_name='my_order',
            name='order_status',
            field=models.BooleanField(null=True, verbose_name='Dlivered'),
        ),
    ]
